/**
 * Known API provider presets.
 * Each preset defines the service name, credential type, URL patterns,
 * injection config, and a validation endpoint to test the key.
 */

export interface ProviderPreset {
  name: string;
  displayName: string;
  type: "bearer" | "api_key" | "basic" | "oauth2_pkce";
  patterns: string[];
  injectMethod: "header" | "query_param";
  injectName: string;
  injectTemplate: string;
  /** URL to GET with the credential to validate it. Expects 2xx on success. */
  validateUrl: string;
  /** Expected status codes that mean "key is valid" (default: [200]) */
  validateOk?: number[];
  /** Hint shown to user about where to get the key */
  keyHint: string;
  /** OAuth2 PKCE config — present only when type is "oauth2_pkce" */
  oauth?: {
    authorizeUrl: string;
    tokenUrl: string;
    scopes: string;
  };
}

export const PROVIDERS: ProviderPreset[] = [
  {
    name: "github",
    displayName: "GitHub",
    type: "bearer",
    patterns: ["*.github.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://api.github.com/user",
    keyHint: "https://github.com/settings/tokens",
  },
  {
    name: "gitlab",
    displayName: "GitLab",
    type: "bearer",
    patterns: ["*.gitlab.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://gitlab.com/api/v4/user",
    keyHint: "https://gitlab.com/-/user_settings/personal_access_tokens",
  },
  {
    name: "openai",
    displayName: "OpenAI",
    type: "bearer",
    patterns: ["api.openai.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://api.openai.com/v1/models",
    keyHint: "https://platform.openai.com/api-keys",
  },
  {
    name: "anthropic",
    displayName: "Anthropic",
    type: "api_key",
    patterns: ["api.anthropic.com"],
    injectMethod: "header",
    injectName: "x-api-key",
    injectTemplate: "{token}",
    validateUrl: "https://api.anthropic.com/v1/messages",
    validateOk: [400], // 400 = key valid but missing body; 401 = bad key
    keyHint: "https://console.anthropic.com/settings/keys",
  },
  {
    name: "google-ai",
    displayName: "Google AI (Gemini)",
    type: "api_key",
    patterns: ["generativelanguage.googleapis.com"],
    injectMethod: "query_param",
    injectName: "key",
    injectTemplate: "{token}",
    validateUrl: "https://generativelanguage.googleapis.com/v1/models",
    keyHint: "https://aistudio.google.com/app/apikey",
  },
  {
    name: "elevenlabs",
    displayName: "ElevenLabs",
    type: "api_key",
    patterns: ["api.elevenlabs.io"],
    injectMethod: "header",
    injectName: "xi-api-key",
    injectTemplate: "{token}",
    validateUrl: "https://api.elevenlabs.io/v1/user",
    keyHint: "https://elevenlabs.io/app/settings/api-keys",
  },
  {
    name: "stripe",
    displayName: "Stripe",
    type: "bearer",
    patterns: ["api.stripe.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://api.stripe.com/v1/balance",
    keyHint: "https://dashboard.stripe.com/apikeys",
  },
  {
    name: "slack",
    displayName: "Slack",
    type: "bearer",
    patterns: ["slack.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://slack.com/api/auth.test",
    keyHint: "https://api.slack.com/apps → OAuth & Permissions → Bot Token",
  },
  {
    name: "discord",
    displayName: "Discord",
    type: "bearer",
    patterns: ["discord.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bot {token}",
    validateUrl: "https://discord.com/api/v10/users/@me",
    keyHint: "https://discord.com/developers/applications → Bot → Token",
  },
  {
    name: "notion",
    displayName: "Notion",
    type: "bearer",
    patterns: ["api.notion.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://api.notion.com/v1/users/me",
    keyHint: "https://www.notion.so/my-integrations",
  },
  {
    name: "linear",
    displayName: "Linear",
    type: "bearer",
    patterns: ["api.linear.app"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "{token}",
    validateUrl: "https://api.linear.app/graphql",
    validateOk: [400], // GraphQL needs a body; 400 = auth ok, 401 = bad key
    keyHint: "https://linear.app/settings/api",
  },
  {
    name: "vercel",
    displayName: "Vercel",
    type: "bearer",
    patterns: ["api.vercel.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://api.vercel.com/v2/user",
    keyHint: "https://vercel.com/account/tokens",
  },
  {
    name: "supabase",
    displayName: "Supabase",
    type: "bearer",
    patterns: ["*.supabase.co"],
    injectMethod: "header",
    injectName: "apikey",
    injectTemplate: "{token}",
    validateUrl: "", // No generic validation endpoint
    keyHint: "Project Settings → API → anon/service_role key",
  },
  {
    name: "cloudflare",
    displayName: "Cloudflare",
    type: "bearer",
    patterns: ["api.cloudflare.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://api.cloudflare.com/client/v4/user/tokens/verify",
    keyHint: "https://dash.cloudflare.com/profile/api-tokens",
  },
  {
    name: "resend",
    displayName: "Resend",
    type: "bearer",
    patterns: ["api.resend.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://api.resend.com/api-keys",
    keyHint: "https://resend.com/api-keys",
  },
  {
    name: "twilio",
    displayName: "Twilio",
    type: "basic",
    patterns: ["api.twilio.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Basic {token}",
    validateUrl: "https://api.twilio.com/2010-04-01/Accounts.json",
    keyHint: "https://console.twilio.com → Account SID:Auth Token (as user:pass)",
  },
  {
    name: "sendgrid",
    displayName: "SendGrid",
    type: "bearer",
    patterns: ["api.sendgrid.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://api.sendgrid.com/v3/user/profile",
    keyHint: "https://app.sendgrid.com/settings/api_keys",
  },
  {
    name: "replicate",
    displayName: "Replicate",
    type: "bearer",
    patterns: ["api.replicate.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://api.replicate.com/v1/account",
    keyHint: "https://replicate.com/account/api-tokens",
  },
  {
    name: "huggingface",
    displayName: "Hugging Face",
    type: "bearer",
    patterns: ["api-inference.huggingface.co", "huggingface.co"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://huggingface.co/api/whoami-v2",
    keyHint: "https://huggingface.co/settings/tokens",
  },
  {
    name: "google-cloud",
    displayName: "Google Cloud / APIs",
    type: "bearer",
    patterns: ["*.googleapis.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://www.googleapis.com/oauth2/v1/tokeninfo",
    validateOk: [200, 400],
    keyHint: "https://console.cloud.google.com/apis/credentials (OAuth2 token or service account)",
  },
  {
    name: "mistral",
    displayName: "Mistral AI",
    type: "bearer",
    patterns: ["api.mistral.ai"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://api.mistral.ai/v1/models",
    keyHint: "https://console.mistral.ai/api-keys",
  },
  {
    name: "groq",
    displayName: "Groq",
    type: "bearer",
    patterns: ["api.groq.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://api.groq.com/openai/v1/models",
    keyHint: "https://console.groq.com/keys",
  },
  {
    name: "together",
    displayName: "Together AI",
    type: "bearer",
    patterns: ["api.together.xyz"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://api.together.xyz/v1/models",
    keyHint: "https://api.together.xyz/settings/api-keys",
  },
  {
    name: "perplexity",
    displayName: "Perplexity",
    type: "bearer",
    patterns: ["api.perplexity.ai"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://api.perplexity.ai/chat/completions",
    validateOk: [400, 422],
    keyHint: "https://www.perplexity.ai/settings/api",
  },
  {
    name: "cohere",
    displayName: "Cohere",
    type: "bearer",
    patterns: ["api.cohere.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://api.cohere.com/v2/models",
    keyHint: "https://dashboard.cohere.com/api-keys",
  },
  {
    name: "deepseek",
    displayName: "DeepSeek",
    type: "bearer",
    patterns: ["api.deepseek.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://api.deepseek.com/models",
    keyHint: "https://platform.deepseek.com/api_keys",
  },
  {
    name: "fireworks",
    displayName: "Fireworks AI",
    type: "bearer",
    patterns: ["api.fireworks.ai"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://api.fireworks.ai/inference/v1/models",
    keyHint: "https://fireworks.ai/account/api-keys",
  },
  {
    name: "stability",
    displayName: "Stability AI",
    type: "bearer",
    patterns: ["api.stability.ai"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://api.stability.ai/v1/user/account",
    keyHint: "https://platform.stability.ai/account/keys",
  },
  {
    name: "pinecone",
    displayName: "Pinecone",
    type: "api_key",
    patterns: ["*.pinecone.io"],
    injectMethod: "header",
    injectName: "Api-Key",
    injectTemplate: "{token}",
    validateUrl: "https://api.pinecone.io/indexes",
    keyHint: "https://app.pinecone.io → API Keys",
  },
  {
    name: "airtable",
    displayName: "Airtable",
    type: "bearer",
    patterns: ["api.airtable.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://api.airtable.com/v0/meta/whoami",
    keyHint: "https://airtable.com/create/tokens",
  },
  {
    name: "figma",
    displayName: "Figma",
    type: "bearer",
    patterns: ["api.figma.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://api.figma.com/v1/me",
    keyHint: "https://www.figma.com/developers/api#access-tokens",
  },
  {
    name: "jira",
    displayName: "Jira / Atlassian",
    type: "basic",
    patterns: ["*.atlassian.net"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Basic {token}",
    validateUrl: "",
    keyHint: "https://id.atlassian.com/manage-profile/security/api-tokens (email:token)",
  },
  {
    name: "bitbucket",
    displayName: "Bitbucket",
    type: "basic",
    patterns: ["api.bitbucket.org"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Basic {token}",
    validateUrl: "https://api.bitbucket.org/2.0/user",
    keyHint: "https://bitbucket.org/account/settings/app-passwords/ (user:app-password)",
  },
  {
    name: "datadog",
    displayName: "Datadog",
    type: "api_key",
    patterns: ["api.datadoghq.com", "*.datadoghq.com"],
    injectMethod: "header",
    injectName: "DD-API-KEY",
    injectTemplate: "{token}",
    validateUrl: "https://api.datadoghq.com/api/v1/validate",
    keyHint: "https://app.datadoghq.com/organization-settings/api-keys",
  },
  {
    name: "sentry",
    displayName: "Sentry",
    type: "bearer",
    patterns: ["sentry.io"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://sentry.io/api/0/",
    keyHint: "https://sentry.io/settings/account/api/auth-tokens/",
  },
  {
    name: "planetscale",
    displayName: "PlanetScale",
    type: "bearer",
    patterns: ["api.planetscale.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "{token}",
    validateUrl: "https://api.planetscale.com/v1/organizations",
    keyHint: "https://app.planetscale.com/settings/service-tokens",
  },
  {
    name: "neon",
    displayName: "Neon",
    type: "bearer",
    patterns: ["console.neon.tech"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://console.neon.tech/api/v2/projects",
    keyHint: "https://console.neon.tech/app/settings/api-keys",
  },
  {
    name: "turso",
    displayName: "Turso",
    type: "bearer",
    patterns: ["api.turso.tech"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://api.turso.tech/v1/organizations",
    keyHint: "https://turso.tech/app → Settings → Platform API Tokens",
  },
  {
    name: "upstash",
    displayName: "Upstash",
    type: "bearer",
    patterns: ["api.upstash.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://api.upstash.com/v2/redis/databases",
    keyHint: "https://console.upstash.com/account/api",
  },
  {
    name: "spotify",
    displayName: "Spotify",
    type: "bearer",
    patterns: ["api.spotify.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://api.spotify.com/v1/me",
    keyHint: "https://developer.spotify.com/dashboard",
  },
  {
    name: "twitter",
    displayName: "X / Twitter",
    type: "bearer",
    patterns: ["api.twitter.com", "api.x.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://api.twitter.com/2/users/me",
    keyHint: "https://developer.twitter.com/en/portal/dashboard",
  },
  {
    name: "youtube",
    displayName: "YouTube Data API",
    type: "api_key",
    patterns: ["www.googleapis.com/youtube"],
    injectMethod: "query_param",
    injectName: "key",
    injectTemplate: "{token}",
    validateUrl: "https://www.googleapis.com/youtube/v3/channels?part=id&mine=true",
    validateOk: [400],
    keyHint: "https://console.cloud.google.com/apis/credentials",
  },
  {
    name: "maps",
    displayName: "Google Maps",
    type: "api_key",
    patterns: ["maps.googleapis.com"],
    injectMethod: "query_param",
    injectName: "key",
    injectTemplate: "{token}",
    validateUrl: "https://maps.googleapis.com/maps/api/geocode/json?address=test",
    keyHint: "https://console.cloud.google.com/apis/credentials",
  },
  {
    name: "shopify",
    displayName: "Shopify",
    type: "bearer",
    patterns: ["*.myshopify.com"],
    injectMethod: "header",
    injectName: "X-Shopify-Access-Token",
    injectTemplate: "{token}",
    validateUrl: "",
    keyHint: "Shopify Admin → Settings → Apps → Develop apps → API credentials",
  },
  {
    name: "mailgun",
    displayName: "Mailgun",
    type: "basic",
    patterns: ["api.mailgun.net"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Basic {token}",
    validateUrl: "https://api.mailgun.net/v3/domains",
    keyHint: "https://app.mailgun.com/settings/api_security (api:key-xxx)",
  },
  {
    name: "postmark",
    displayName: "Postmark",
    type: "api_key",
    patterns: ["api.postmarkapp.com"],
    injectMethod: "header",
    injectName: "X-Postmark-Server-Token",
    injectTemplate: "{token}",
    validateUrl: "https://api.postmarkapp.com/server",
    keyHint: "https://account.postmarkapp.com/servers → API Tokens",
  },
  {
    name: "assemblyai",
    displayName: "AssemblyAI",
    type: "api_key",
    patterns: ["api.assemblyai.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "{token}",
    validateUrl: "https://api.assemblyai.com/v2/transcript",
    validateOk: [400],
    keyHint: "https://www.assemblyai.com/app/account",
  },
  {
    name: "deepgram",
    displayName: "Deepgram",
    type: "bearer",
    patterns: ["api.deepgram.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Token {token}",
    validateUrl: "https://api.deepgram.com/v1/projects",
    keyHint: "https://console.deepgram.com → API Keys",
  },
  {
    name: "openrouter",
    displayName: "OpenRouter",
    type: "bearer",
    patterns: ["openrouter.ai"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://openrouter.ai/api/v1/models",
    keyHint: "https://openrouter.ai/keys",
  },
  {
    name: "fly",
    displayName: "Fly.io",
    type: "bearer",
    patterns: ["api.machines.dev", "api.fly.io"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://api.machines.dev/v1/apps",
    keyHint: "https://fly.io/user/personal_access_tokens",
  },
  {
    name: "railway",
    displayName: "Railway",
    type: "bearer",
    patterns: ["backboard.railway.app"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://backboard.railway.app/graphql/v2",
    validateOk: [400],
    keyHint: "https://railway.app/account/tokens",
  },
  {
    name: "render",
    displayName: "Render",
    type: "bearer",
    patterns: ["api.render.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://api.render.com/v1/owners",
    keyHint: "https://dashboard.render.com/u/settings#api-keys",
  },
  {
    name: "digitalocean",
    displayName: "DigitalOcean",
    type: "bearer",
    patterns: ["api.digitalocean.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://api.digitalocean.com/v2/account",
    keyHint: "https://cloud.digitalocean.com/account/api/tokens",
  },
  {
    name: "hetzner",
    displayName: "Hetzner",
    type: "bearer",
    patterns: ["api.hetzner.cloud"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://api.hetzner.cloud/v1/servers",
    keyHint: "https://console.hetzner.cloud → Security → API Tokens",
  },
  {
    name: "linode",
    displayName: "Linode / Akamai",
    type: "bearer",
    patterns: ["api.linode.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://api.linode.com/v4/profile",
    keyHint: "https://cloud.linode.com/profile/tokens",
  },
  {
    name: "doppler",
    displayName: "Doppler",
    type: "bearer",
    patterns: ["api.doppler.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://api.doppler.com/v3/me",
    keyHint: "https://dashboard.doppler.com → Access → Service Tokens",
  },
  {
    name: "lemon-squeezy",
    displayName: "Lemon Squeezy",
    type: "bearer",
    patterns: ["api.lemonsqueezy.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://api.lemonsqueezy.com/v1/users/me",
    keyHint: "https://app.lemonsqueezy.com/settings/api",
  },
  {
    name: "paddle",
    displayName: "Paddle",
    type: "bearer",
    patterns: ["api.paddle.com", "sandbox-api.paddle.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://api.paddle.com/products",
    keyHint: "https://vendors.paddle.com/authentication",
  },

  // ── OAuth2 PKCE providers ──────────────────────────────────────────────

  // Google
  {
    name: "gmail",
    displayName: "Gmail (OAuth2)",
    type: "oauth2_pkce",
    patterns: ["gmail.googleapis.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://gmail.googleapis.com/gmail/v1/users/me/profile",
    keyHint: "https://console.cloud.google.com/apis/credentials → OAuth 2.0 Client ID",
    oauth: {
      authorizeUrl: "https://accounts.google.com/o/oauth2/v2/auth",
      tokenUrl: "https://oauth2.googleapis.com/token",
      scopes: "https://www.googleapis.com/auth/gmail.modify",
    },
  },
  {
    name: "google-drive",
    displayName: "Google Drive (OAuth2)",
    type: "oauth2_pkce",
    patterns: ["www.googleapis.com/drive", "www.googleapis.com/upload/drive"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://www.googleapis.com/drive/v3/about?fields=user",
    keyHint: "https://console.cloud.google.com/apis/credentials → OAuth 2.0 Client ID",
    oauth: {
      authorizeUrl: "https://accounts.google.com/o/oauth2/v2/auth",
      tokenUrl: "https://oauth2.googleapis.com/token",
      scopes: "https://www.googleapis.com/auth/drive",
    },
  },
  {
    name: "google-sheets",
    displayName: "Google Sheets (OAuth2)",
    type: "oauth2_pkce",
    patterns: ["sheets.googleapis.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "",
    keyHint: "https://console.cloud.google.com/apis/credentials → OAuth 2.0 Client ID",
    oauth: {
      authorizeUrl: "https://accounts.google.com/o/oauth2/v2/auth",
      tokenUrl: "https://oauth2.googleapis.com/token",
      scopes: "https://www.googleapis.com/auth/spreadsheets",
    },
  },
  {
    name: "google-calendar",
    displayName: "Google Calendar (OAuth2)",
    type: "oauth2_pkce",
    patterns: ["www.googleapis.com/calendar"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://www.googleapis.com/calendar/v3/calendars/primary",
    keyHint: "https://console.cloud.google.com/apis/credentials → OAuth 2.0 Client ID",
    oauth: {
      authorizeUrl: "https://accounts.google.com/o/oauth2/v2/auth",
      tokenUrl: "https://oauth2.googleapis.com/token",
      scopes: "https://www.googleapis.com/auth/calendar",
    },
  },

  // Microsoft
  {
    name: "microsoft-graph",
    displayName: "Microsoft Graph (OAuth2)",
    type: "oauth2_pkce",
    patterns: ["graph.microsoft.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://graph.microsoft.com/v1.0/me",
    keyHint: "https://portal.azure.com → App registrations → New registration",
    oauth: {
      authorizeUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
      tokenUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/token",
      scopes: "User.Read Mail.Read",
    },
  },
  {
    name: "outlook",
    displayName: "Outlook Mail (OAuth2)",
    type: "oauth2_pkce",
    patterns: ["graph.microsoft.com/v1.0/me/messages", "graph.microsoft.com/v1.0/me/mailFolders"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://graph.microsoft.com/v1.0/me",
    keyHint: "https://portal.azure.com → App registrations",
    oauth: {
      authorizeUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
      tokenUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/token",
      scopes: "User.Read Mail.ReadWrite",
    },
  },
  {
    name: "onedrive",
    displayName: "OneDrive (OAuth2)",
    type: "oauth2_pkce",
    patterns: ["graph.microsoft.com/v1.0/me/drive"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://graph.microsoft.com/v1.0/me/drive",
    keyHint: "https://portal.azure.com → App registrations",
    oauth: {
      authorizeUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
      tokenUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/token",
      scopes: "Files.ReadWrite",
    },
  },

  // Other OAuth2 services
  {
    name: "slack-oauth",
    displayName: "Slack (OAuth2)",
    type: "oauth2_pkce",
    patterns: ["slack.com/api"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://slack.com/api/auth.test",
    keyHint: "https://api.slack.com/apps → OAuth & Permissions",
    oauth: {
      authorizeUrl: "https://slack.com/oauth/v2/authorize",
      tokenUrl: "https://slack.com/api/oauth.v2.access",
      scopes: "chat:write channels:read",
    },
  },
  {
    name: "spotify-oauth",
    displayName: "Spotify (OAuth2)",
    type: "oauth2_pkce",
    patterns: ["api.spotify.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://api.spotify.com/v1/me",
    keyHint: "https://developer.spotify.com/dashboard → Create app",
    oauth: {
      authorizeUrl: "https://accounts.spotify.com/authorize",
      tokenUrl: "https://accounts.spotify.com/api/token",
      scopes: "user-read-private user-read-email",
    },
  },
  {
    name: "github-oauth",
    displayName: "GitHub (OAuth2)",
    type: "oauth2_pkce",
    patterns: ["api.github.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://api.github.com/user",
    keyHint: "https://github.com/settings/developers → OAuth Apps",
    oauth: {
      authorizeUrl: "https://github.com/login/oauth/authorize",
      tokenUrl: "https://github.com/login/oauth/access_token",
      scopes: "repo user",
    },
  },
  {
    name: "dropbox",
    displayName: "Dropbox (OAuth2)",
    type: "oauth2_pkce",
    patterns: ["api.dropboxapi.com", "content.dropboxapi.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://api.dropboxapi.com/2/users/get_current_account",
    validateOk: [200, 400],
    keyHint: "https://www.dropbox.com/developers/apps → Create app",
    oauth: {
      authorizeUrl: "https://www.dropbox.com/oauth2/authorize",
      tokenUrl: "https://api.dropboxapi.com/oauth2/token",
      scopes: "",
    },
  },
  {
    name: "zoom",
    displayName: "Zoom (OAuth2)",
    type: "oauth2_pkce",
    patterns: ["api.zoom.us"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://api.zoom.us/v2/users/me",
    keyHint: "https://marketplace.zoom.us → Develop → Build App → OAuth",
    oauth: {
      authorizeUrl: "https://zoom.us/oauth/authorize",
      tokenUrl: "https://zoom.us/oauth/token",
      scopes: "user:read",
    },
  },
  {
    name: "linkedin",
    displayName: "LinkedIn (OAuth2)",
    type: "oauth2_pkce",
    patterns: ["api.linkedin.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://api.linkedin.com/v2/userinfo",
    keyHint: "https://www.linkedin.com/developers/apps",
    oauth: {
      authorizeUrl: "https://www.linkedin.com/oauth/v2/authorization",
      tokenUrl: "https://www.linkedin.com/oauth/v2/accessToken",
      scopes: "openid profile email",
    },
  },
  {
    name: "hubspot",
    displayName: "HubSpot (OAuth2)",
    type: "oauth2_pkce",
    patterns: ["api.hubapi.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://api.hubapi.com/account-info/v3/api-usage/daily/private-apps",
    validateOk: [200, 403],
    keyHint: "https://developers.hubspot.com → Apps → Create app",
    oauth: {
      authorizeUrl: "https://app.hubspot.com/oauth/authorize",
      tokenUrl: "https://api.hubapi.com/oauth/v1/token",
      scopes: "crm.objects.contacts.read",
    },
  },
  {
    name: "salesforce",
    displayName: "Salesforce (OAuth2)",
    type: "oauth2_pkce",
    patterns: ["*.salesforce.com", "*.my.salesforce.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "",
    keyHint: "Setup → Apps → App Manager → New Connected App",
    oauth: {
      authorizeUrl: "https://login.salesforce.com/services/oauth2/authorize",
      tokenUrl: "https://login.salesforce.com/services/oauth2/token",
      scopes: "api refresh_token",
    },
  },
  {
    name: "twitch",
    displayName: "Twitch (OAuth2)",
    type: "oauth2_pkce",
    patterns: ["api.twitch.tv"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://api.twitch.tv/helix/users",
    keyHint: "https://dev.twitch.tv/console/apps",
    oauth: {
      authorizeUrl: "https://id.twitch.tv/oauth2/authorize",
      tokenUrl: "https://id.twitch.tv/oauth2/token",
      scopes: "user:read:email",
    },
  },
  {
    name: "reddit",
    displayName: "Reddit (OAuth2)",
    type: "oauth2_pkce",
    patterns: ["oauth.reddit.com"],
    injectMethod: "header",
    injectName: "Authorization",
    injectTemplate: "Bearer {token}",
    validateUrl: "https://oauth.reddit.com/api/v1/me",
    keyHint: "https://www.reddit.com/prefs/apps → Create application",
    oauth: {
      authorizeUrl: "https://www.reddit.com/api/v1/authorize",
      tokenUrl: "https://www.reddit.com/api/v1/access_token",
      scopes: "identity read",
    },
  },
];

export function findProvider(query: string): ProviderPreset | undefined {
  const q = query.toLowerCase();
  return PROVIDERS.find(
    (p) => p.name === q || p.displayName.toLowerCase() === q,
  );
}

export function searchProviders(query: string): ProviderPreset[] {
  if (!query) return PROVIDERS;
  const q = query.toLowerCase();
  return PROVIDERS.filter(
    (p) =>
      p.name.includes(q) ||
      p.displayName.toLowerCase().includes(q),
  );
}
